apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: go-hostname
spec:
  image: harbor.mbentley.net/mbentley/go-hostname:latest@sha256:66d37dc11abc4c02cc63479fccbcbd5eeda1851db84142e8455d7900ce794d1f
  replicas: 1
  ports:
  - name: main
    port: 8080
